package woa.drools

// Sumamos el importe total de los productos
rule "Initial rule"
	salience 20
    when
        order : Order ();
        totalPrice : Double() from accumulate (
        	Product( productPrice : price) from order.getProducts,
        	init (double total = 0;),
        	action (total += productPrice;),
        	result (new Double(total))
        );
    then
    	order.setTotalPrice(totalPrice);
end
